import http from 'http';
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { fileURLToPath } from 'url';
import { load, save, id, now, hashPassword, createSession, userByToken } from './db.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const publicDir = path.join(root, 'public');
const uploadDir = path.join(process.env.UPLOAD_DIR || path.join(root, 'uploads'));
fs.mkdirSync(uploadDir, { recursive: true });
let db = load();
const collections = ['users','yards','categories','assets','images','storageCharges','history','inquiries','messages','auditLogs','sessions','transactions','reservations','offers','expenses','notifications','contracts','settings','locations','invoices','conditionReports'];
for (const k of collections) db[k] ||= [];
const port = Number(process.env.PORT || 3000);
const roles = ['ADMIN','MANAGER','RECEPTION','SALES','YARD','ACCOUNTING','CUSTOMER'];
const identityTypes = ['NATIONAL_ID','RESIDENCY_ID','PASSPORT','OTHER'];
const currencies = [
  {code:'SAR',name:'الريال السعودي',symbol:'ر.س',locale:'ar-SA'},
  {code:'YER',name:'الريال اليمني',symbol:'ر.ي',locale:'ar-YE'},
  {code:'USD',name:'الدولار الأمريكي',symbol:'$',locale:'en-US'},
  {code:'AED',name:'الدرهم الإماراتي',symbol:'د.إ',locale:'ar-AE'},
  {code:'KWD',name:'الدينار الكويتي',symbol:'د.ك',locale:'ar-KW'},
  {code:'QAR',name:'الريال القطري',symbol:'ر.ق',locale:'ar-QA'}
];
const mime={'.html':'text/html;charset=utf-8','.js':'text/javascript;charset=utf-8','.css':'text/css;charset=utf-8','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml'};
function send(res,status,data,type='json'){res.statusCode=status;res.setHeader('Content-Type',type);res.end(type==='json'?JSON.stringify(data):data)}
function cookie(res,name,value,maxAge=604800){res.setHeader('Set-Cookie',`${name}=${value}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}${process.env.NODE_ENV==='production'?'; Secure':''}`)}
function clearCookie(res,name){cookie(res,name,'',0)}
async function body(req){return await new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>12e6)req.destroy()});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch{resolve({})}});req.on('error',reject)})}
function auth(req){const h=req.headers.authorization?.replace('Bearer ','');const c=(req.headers.cookie||'').match(/(?:^|; )token=([^;]+)/)?.[1];return userByToken(db,h||c)}
function requireRole(req,res,allowed=roles){const u=auth(req);if(!u){send(res,401,{error:'تسجيل الدخول مطلوب'});return null}if(!allowed.includes(u.role)){send(res,403,{error:'ليس لديك صلاحية لهذه العملية'});return null}return u}
const category=v=>db.categories.find(x=>x.id===v); const yard=v=>db.yards.find(x=>x.id===v); const user=v=>db.users.find(x=>x.id===v); const asset=v=>db.assets.find(x=>x.id===v);
const setting=(key,def='')=>db.settings.find(x=>x.key===key)?.value??def;
function upsertSetting(key,value){const x=db.settings.find(s=>s.key===key);if(x)x.value=value;else db.settings.push({id:id('set'),key,value})}
function systemSettings(){const c=currencies.find(x=>x.code===setting('currency','SAR'))||currencies[0];return {name:setting('name','حوشك'),tagline:setting('tagline','منصة إدارة وعرض ووساطة المركبات والمعدات والأصول'),country:setting('country','السعودية'),city:setting('city','الرياض'),whatsapp:setting('whatsapp','0500000000'),phone:setting('phone',''),email:setting('email',''),address:setting('address',''),logo:setting('logo',''),currency:c.code,currencyName:c.name,currencySymbol:c.symbol,timezone:setting('timezone','Asia/Riyadh'),language:setting('language','ar'),storageDefaultRate:Number(setting('storageDefaultRate','15'))}}
function safeUser(u){return {id:u.id,name:u.name,phone:u.phone,role:u.role,active:u.active,identityType:u.identityType||'NATIONAL_ID',identityNumber:u.identityNumber||'',email:u.email||'',address:u.address||'',createdAt:u.createdAt}}
function audit(u,action,entity,entityId,details={}){db.auditLogs.push({id:id('audit'),userId:u?.id||null,action,entity,entityId,details,createdAt:now()})}
function notify(userId,title,message,type='INFO'){if(!userId)return;db.notifications.push({id:id('not'),userId,title,message,type,read:false,createdAt:now()})}
function deriveVisibility(purpose,status,override='AUTO'){if(override==='HIDE')return false;if(override==='SHOW')return ['ACTIVE','RESERVED'].includes(status);return ['SALE','RENT','SALE_RENT'].includes(purpose)&&['ACTIVE','RESERVED'].includes(status)}
export {deriveVisibility};
function refreshVisibility(a){a.publicVisible=deriveVisibility(a.purpose,a.status,a.publishOverride||'AUTO');return a}
function addHistory(a,u,old,note){db.history.push({id:id('hist'),assetId:a.id,fromPurpose:old?.purpose??null,toPurpose:a.purpose,fromStatus:old?.status??null,toStatus:a.status,note,changedById:u?.id||null,createdAt:now()})}
function activeStorage(a){return db.storageCharges.find(c=>c.assetId===a.id&&!c.toAt)}
function storageAccrued(a){const c=activeStorage(a);if(!c)return {days:0,current:0,charge:null};const from=new Date(c.fromAt).getTime();const end=a.exitAt?new Date(a.exitAt).getTime():Date.now();const days=Math.max(1,Math.ceil(Math.max(0,end-from)/86400000));return {days,current:days*Number(c.dailyRate||0),charge:c}}
function startStorage(a,rate){if(activeStorage(a))return activeStorage(a);const c={id:id('chg'),assetId:a.id,fromAt:a.entryAt||now(),toAt:null,dailyRate:Number(rate||0),total:null,paid:0,balance:0,createdAt:now(),updatedAt:now()};db.storageCharges.push(c);return c}
function closeStorage(a,paid=0){const c=activeStorage(a);if(!c)return null;const acc=storageAccrued(a);c.toAt=a.exitAt||now();c.total=acc.current;c.paid=Number(c.paid||0)+Number(paid||0);c.balance=Math.max(0,c.total-c.paid);c.updatedAt=now();return c}
function images(a){return db.images.filter(i=>i.assetId===a.id).sort((x,y)=>(x.sortOrder||0)-(y.sortOrder||0))}
function publicAsset(a){return {...a,category:category(a.categoryId),yard:yard(a.yardId),images:images(a),currency:systemSettings().currency,currencySymbol:systemSettings().currencySymbol}}
function adminAsset(a){const o=user(a.ownerId);return {...publicAsset(a),owner:o?safeUser(o):null,storage:storageAccrued(a),history:db.history.filter(h=>h.assetId===a.id).sort((x,y)=>new Date(y.createdAt)-new Date(x.createdAt)),conditions:db.conditionReports.filter(x=>x.assetId===a.id).sort((x,y)=>new Date(y.createdAt)-new Date(x.createdAt))}}
function match(a,q){const s=String(q||'').trim().toLowerCase();if(!s)return true;return [a.code,a.title,a.make,a.model,a.plateNumber,a.variant,a.locationCode,a.color].filter(Boolean).some(x=>String(x).toLowerCase().includes(s))}
function validatePurpose(c,p){return (p==='SALE'&&c?.allowSale)||(p==='RENT'&&c?.allowRent)||(p==='STORAGE'&&c?.allowStorage)||(p==='SALE_RENT'&&c?.allowSale&&c?.allowRent)}
function createAsset(b,u){const c=category(b.categoryId);if(!b.title||!c||!b.ownerId||!b.yardId||!b.purpose)throw Error('العنوان والقسم والمالك والساحة والغرض مطلوبة');if(!validatePurpose(c,b.purpose))throw Error('القسم لا يسمح بهذا النوع');const a={id:id('ast'),code:b.code||`HSH-${String(Date.now()).slice(-8)}`,title:b.title,description:b.description||'',ownerId:b.ownerId,categoryId:b.categoryId,yardId:b.yardId,purpose:b.purpose,status:b.status||'ACTIVE',salePrice:b.salePrice===''||b.salePrice==null?null:Number(b.salePrice),rentPrice:b.rentPrice===''||b.rentPrice==null?null:Number(b.rentPrice),rentUnit:b.rentUnit||'يوم',dailyStorageFee:Number(b.dailyStorageFee??systemSettings().storageDefaultRate),make:b.make||'',model:b.model||'',year:b.year?Number(b.year):null,color:b.color||'',variant:b.variant||'',plateNumber:b.plateNumber||'',locationCode:b.locationCode||'',publishOverride:b.publishOverride||'AUTO',publicVisible:false,entryAt:b.entryAt||now(),exitAt:null,exitReason:null,exitNote:'',customFields:b.customFields||{},entryNotes:b.entryNotes||'',createdAt:now(),updatedAt:now()};refreshVisibility(a);db.assets.push(a);addHistory(a,u,null,'إدخال أصل جديد');if(a.purpose==='STORAGE')startStorage(a,a.dailyStorageFee);audit(u,'CREATE','ASSET',a.id,{purpose:a.purpose});return a}
function publicSearch(a,q,purpose,categoryId,min,max,city){if(!deriveVisibility(a.purpose,a.status,a.publishOverride||'AUTO'))return false;if(!match(a,q)||categoryId&&a.categoryId!==categoryId)return false;if(city&&yard(a.yardId)?.city!==city)return false;if(purpose==='SALE'&&!['SALE','SALE_RENT'].includes(a.purpose))return false;if(purpose==='RENT'&&!['RENT','SALE_RENT'].includes(a.purpose))return false;const price=purpose==='RENT'?Number(a.rentPrice||0):Number(a.salePrice||0);if(min!==null&&min!==''&&price<Number(min))return false;if(max!==null&&max!==''&&price>Number(max))return false;return true}
function commissionValue(c){return c.commissionType==='PERCENT'?Number(c.amount||0)*Number(c.commissionRate||0)/100:Number(c.commissionFixed||0)}
function nextInvoiceNo(){const y=new Date().getFullYear();const n=db.invoices.filter(i=>String(i.number).startsWith(`INV-${y}-`)).length+1;return `INV-${y}-${String(n).padStart(5,'0')}`}
async function route(req,res){
 const url=new URL(req.url,`http://${req.headers.host||'localhost'}`),p=url.pathname,method=req.method;
 if(p==='/api/health'&&method==='GET')return send(res,200,{ok:true,service:'houshak',version:'2.1.0',time:now()});
 if(p==='/api/currencies'&&method==='GET')return send(res,200,currencies);
 if(p==='/api/identity-types'&&method==='GET')return send(res,200,[{code:'NATIONAL_ID',name:'هوية وطنية / شخصية'},{code:'RESIDENCY_ID',name:'هوية مقيم'},{code:'PASSPORT',name:'جواز سفر'},{code:'OTHER',name:'هوية أخرى'}]);
 if(p==='/api/auth/login'&&method==='POST'){const b=await body(req),u=db.users.find(x=>x.phone===b.phone&&x.active);if(!u||u.passwordHash!==hashPassword(b.password||''))return send(res,401,{error:'بيانات الدخول غير صحيحة'});const t=createSession(db,u.id);save(db);cookie(res,'token',t);return send(res,200,{user:safeUser(u)})}
 if(p==='/api/auth/logout'&&method==='POST'){const h=req.headers.authorization?.replace('Bearer ','');const c=(req.headers.cookie||'').match(/(?:^|; )token=([^;]+)/)?.[1];db.sessions=db.sessions.filter(s=>s.token!==(h||c));save(db);clearCookie(res,'token');return send(res,200,{ok:true})}
 if(p==='/api/auth/me'&&method==='GET'){const u=auth(req);return u?send(res,200,{user:safeUser(u)}):send(res,401,{error:'غير مسجل'})}
 if(p==='/api/categories'&&method==='GET')return send(res,200,db.categories.filter(c=>c.active).sort((a,b)=>a.sortOrder-b.sortOrder));
 if(p==='/api/yards'&&method==='GET')return send(res,200,db.yards.filter(y=>y.active));
 if(p==='/api/public/settings'&&method==='GET')return send(res,200,systemSettings());
 if(p==='/api/listings'&&method==='GET'){const purpose=url.searchParams.get('purpose'),categoryId=url.searchParams.get('categoryId'),q=url.searchParams.get('q'),min=url.searchParams.get('minPrice'),max=url.searchParams.get('maxPrice'),city=url.searchParams.get('city');const xs=db.assets.filter(a=>publicSearch(a,q,purpose,categoryId,min,max,city));return send(res,200,xs.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).map(publicAsset))}
 if(p.startsWith('/api/listings/')&&method==='GET'){const a=asset(p.split('/')[3]);return a&&deriveVisibility(a.purpose,a.status,a.publishOverride||'AUTO')?send(res,200,publicAsset(a)):send(res,404,{error:'الإعلان غير متاح'})}
 if(p==='/api/inquiries'&&method==='POST'){const b=await body(req),a=asset(b.assetId);if(!a||!deriveVisibility(a.purpose,a.status,a.publishOverride||'AUTO'))return send(res,404,{error:'الإعلان غير متاح'});if(!b.name||!b.phone||!b.message)return send(res,400,{error:'البيانات المطلوبة ناقصة'});const i={id:id('inq'),assetId:a.id,name:b.name,phone:b.phone,message:b.message,status:'OPEN',assignedTo:null,createdAt:now(),updatedAt:now()};db.inquiries.push(i);db.messages.push({id:id('msg'),inquiryId:i.id,senderId:null,body:b.message,createdAt:now()});for(const x of db.users.filter(u=>['ADMIN','MANAGER','SALES'].includes(u.role)&&u.active))notify(x.id,'استفسار جديد',`استفسار عن ${a.title}`,'INQUIRY');save(db);return send(res,201,i)}
 if(p==='/api/reservations'&&method==='POST'){const b=await body(req),a=asset(b.assetId);if(!a||!deriveVisibility(a.purpose,a.status,a.publishOverride||'AUTO'))return send(res,404,{error:'الأصل غير متاح'});if(!b.name||!b.phone||!b.fromAt)return send(res,400,{error:'الاسم والجوال وتاريخ البداية مطلوبة'});if(b.toAt&&new Date(b.toAt)<=new Date(b.fromAt))return send(res,400,{error:'تاريخ النهاية يجب أن يكون بعد البداية'});const overlap=db.reservations.some(r=>r.assetId===a.id&&['PENDING','CONFIRMED'].includes(r.status)&&(!b.toAt||!r.toAt||new Date(b.fromAt)<new Date(r.toAt))&&(!b.toAt||new Date(b.toAt)>new Date(r.fromAt)));if(overlap)return send(res,409,{error:'يوجد حجز متعارض'});let cu=db.users.find(x=>x.phone===b.phone);if(!cu){cu={id:id('usr'),name:b.name,phone:b.phone,passwordHash:hashPassword(crypto.randomUUID()),role:'CUSTOMER',active:true,identityType:b.identityType||'NATIONAL_ID',identityNumber:b.identityNumber||'',createdAt:now()};db.users.push(cu)}const r={id:id('res'),assetId:a.id,customerId:cu.id,fromAt:b.fromAt,toAt:b.toAt||null,status:'PENDING',note:b.note||'',createdAt:now(),updatedAt:now()};db.reservations.push(r);notify(a.ownerId,'طلب حجز جديد',`طلب حجز ${a.title}`,'RESERVATION');save(db);return send(res,201,r)}
 if(p==='/api/offers'&&method==='POST'){const b=await body(req),a=asset(b.assetId);if(!a||!deriveVisibility(a.purpose,a.status,a.publishOverride||'AUTO'))return send(res,404,{error:'الإعلان غير متاح'});if(!b.name||!b.phone||!b.amount)return send(res,400,{error:'الاسم والجوال والعرض مطلوبة'});const o={id:id('off'),assetId:a.id,name:b.name,phone:b.phone,amount:Number(b.amount),note:b.note||'',status:'OPEN',createdAt:now(),updatedAt:now()};db.offers.push(o);for(const x of db.users.filter(u=>['ADMIN','MANAGER','SALES'].includes(u.role)&&u.active))notify(x.id,'عرض شراء جديد',`عرض ${o.amount} على ${a.title}`,'OFFER');save(db);return send(res,201,o)}
 if(p==='/api/public/invoices/'&&method==='GET')return send(res,404,{error:'غير متاح'});
 // Customer/owner portal
 if(p==='/api/my/assets'&&method==='GET'){const u=requireRole(req,res,['CUSTOMER','ADMIN','MANAGER','SALES','RECEPTION','YARD','ACCOUNTING']);if(!u)return;return send(res,200,db.assets.filter(a=>a.ownerId===u.id).map(adminAsset))}
 if(p==='/api/my/notifications'&&method==='GET'){const u=requireRole(req,res);if(!u)return;return send(res,200,db.notifications.filter(n=>n.userId===u.id).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)))}
 if(p==='/api/admin/dashboard'&&method==='GET'){const u=requireRole(req,res,['ADMIN','MANAGER','ACCOUNTING','SALES','RECEPTION','YARD']);if(!u)return;const active=db.assets.filter(a=>a.status!=='EXITED');const income=db.transactions.filter(t=>t.type==='INCOME').reduce((s,t)=>s+Number(t.amount||0),0);const expense=db.transactions.filter(t=>t.type==='EXPENSE').reduce((s,t)=>s+Number(t.amount||0),0);return send(res,200,{system:systemSettings(),counts:{assets:active.length,storage:active.filter(a=>a.purpose==='STORAGE').length,sale:active.filter(a=>['SALE','SALE_RENT'].includes(a.purpose)).length,rent:active.filter(a=>['RENT','SALE_RENT'].includes(a.purpose)).length,reservations:db.reservations.filter(r=>r.status==='PENDING').length,inquiries:db.inquiries.filter(i=>i.status!=='CLOSED').length,offers:db.offers.filter(o=>o.status==='OPEN').length},finance:{income,expense,net:income-expense}})}
 if(p==='/api/admin/assets'&&method==='GET'){const u=requireRole(req,res);if(!u)return;const q=url.searchParams.get('q'),status=url.searchParams.get('status'),purpose=url.searchParams.get('purpose'),categoryId=url.searchParams.get('categoryId'),yardId=url.searchParams.get('yardId'),ownerId=url.searchParams.get('ownerId');let xs=db.assets.filter(a=>match(a,q));if(status)xs=xs.filter(a=>a.status===status);if(purpose)xs=xs.filter(a=>a.purpose===purpose);if(categoryId)xs=xs.filter(a=>a.categoryId===categoryId);if(yardId)xs=xs.filter(a=>a.yardId===yardId);if(ownerId)xs=xs.filter(a=>a.ownerId===ownerId);return send(res,200,xs.sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)).map(adminAsset))}
 if(p==='/api/admin/assets'&&method==='POST'){const u=requireRole(req,res,['ADMIN','MANAGER','RECEPTION','YARD','SALES']);if(!u)return;try{const b=await body(req);const a=createAsset(b,u);save(db);return send(res,201,adminAsset(a))}catch(e){return send(res,400,{error:e.message})}}
 const am=p.match(/^\/api\/admin\/assets\/([^/]+)$/);if(am&&method==='GET'){const u=requireRole(req,res);if(!u)return;const a=asset(am[1]);return a?send(res,200,adminAsset(a)):send(res,404,{error:'الأصل غير موجود'})}
 if(am&&method==='PUT'){const u=requireRole(req,res,['ADMIN','MANAGER','RECEPTION','YARD','SALES']);if(!u)return;const a=asset(am[1]);if(!a)return send(res,404,{error:'الأصل غير موجود'});const b=await body(req);const old={purpose:a.purpose,status:a.status};for(const k of ['title','description','categoryId','yardId','purpose','status','salePrice','rentPrice','rentUnit','dailyStorageFee','make','model','year','color','variant','plateNumber','locationCode','publishOverride','customFields','entryNotes'])if(b[k]!==undefined)a[k]=['salePrice','rentPrice','dailyStorageFee','year'].includes(k)&&b[k]!==''?Number(b[k]):b[k];if(!validatePurpose(category(a.categoryId),a.purpose))return send(res,400,{error:'القسم لا يسمح بهذا الغرض'});if(old.purpose!==a.purpose&&a.purpose==='STORAGE')startStorage(a,a.dailyStorageFee);if(old.purpose==='STORAGE'&&a.purpose!=='STORAGE'&&activeStorage(a))closeStorage(a);refreshVisibility(a);a.updatedAt=now();addHistory(a,u,old,'تعديل الأصل');audit(u,'UPDATE','ASSET',a.id,{old,new:{purpose:a.purpose,status:a.status}});save(db);return send(res,200,adminAsset(a))}
 const ex=p.match(/^\/api\/admin\/assets\/([^/]+)\/exit$/);if(ex&&method==='POST'){const u=requireRole(req,res,['ADMIN','MANAGER','RECEPTION','YARD','SALES']);if(!u)return;const a=asset(ex[1]);if(!a)return send(res,404,{error:'الأصل غير موجود'});const b=await body(req);const old={purpose:a.purpose,status:a.status};a.exitAt=b.exitAt||now();a.exitReason=b.reason||'OTHER';a.exitNote=b.note||'';a.status='EXITED';refreshVisibility(a);const c=closeStorage(a,Number(b.paid||0));addHistory(a,u,old,`خروج: ${a.exitReason}`);audit(u,'EXIT','ASSET',a.id,{reason:a.exitReason});if(c?.balance>0)notify(a.ownerId,'مبلغ تخزين مستحق',`المتبقي على ${a.title}: ${c.balance}`,'PAYMENT_DUE');save(db);return send(res,200,{asset:adminAsset(a),storage:c})}
 const img=p.match(/^\/api\/admin\/assets\/([^/]+)\/images$/);if(img&&method==='POST'){const u=requireRole(req,res,['ADMIN','MANAGER','RECEPTION','YARD','SALES']);if(!u)return;const a=asset(img[1]);if(!a)return send(res,404,{error:'الأصل غير موجود'});const b=await body(req);if(!String(b.dataUrl||'').startsWith('data:image/'))return send(res,400,{error:'ملف صورة غير صالح'});const m=String(b.dataUrl).match(/^data:image\/(png|jpeg|jpg|webp);base64,(.+)$/);if(!m)return send(res,400,{error:'صيغة الصورة غير مدعومة'});const ext=m[1]==='jpeg'?'jpg':m[1];const filename=`${a.id}_${crypto.randomUUID()}.${ext}`;fs.writeFileSync(path.join(uploadDir,filename),Buffer.from(m[2],'base64'));const i={id:id('img'),assetId:a.id,url:`/uploads/${filename}`,filename,sortOrder:db.images.filter(x=>x.assetId===a.id).length,createdAt:now()};db.images.push(i);save(db);return send(res,201,i)}
 if(p==='/api/admin/storage'&&method==='GET'){const u=requireRole(req,res);if(!u)return;return send(res,200,db.storageCharges.map(c=>({...c,asset:asset(c.assetId)?{id:c.assetId,code:asset(c.assetId).code,title:asset(c.assetId).title}:null,accrued:storageAccrued(asset(c.assetId)||{})})).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)))}
 if(p==='/api/admin/storage/payment'&&method==='POST'){const u=requireRole(req,res,['ADMIN','MANAGER','ACCOUNTING','RECEPTION']);if(!u)return;const b=await body(req),c=db.storageCharges.find(x=>x.id===b.chargeId);if(!c)return send(res,404,{error:'رسوم التخزين غير موجودة'});const amount=Number(b.amount||0);c.paid=Number(c.paid||0)+amount;c.balance=Math.max(0,Number(c.total??storageAccrued(asset(c.assetId)||{}).current)-c.paid);db.transactions.push({id:id('txn'),type:'INCOME',category:'STORAGE',amount,assetId:c.assetId,userId:u.id,description:`دفعة تخزين ${asset(c.assetId)?.code||''}`,createdAt:now()});audit(u,'PAYMENT','STORAGE',c.id,{amount});save(db);return send(res,200,c)}
 if(p==='/api/admin/locations'&&method==='GET'){const u=requireRole(req,res);if(!u)return;return send(res,200,db.locations.map(l=>({...l,assetCount:db.assets.filter(a=>a.locationCode===l.code&&a.status!=='EXITED').length})))}
 if(p==='/api/admin/locations'&&method==='POST'){const u=requireRole(req,res,['ADMIN','MANAGER','YARD','RECEPTION']);if(!u)return;const b=await body(req);if(!b.code)return send(res,400,{error:'رمز الموقع مطلوب'});if(db.locations.some(l=>l.code===b.code&&l.yardId===b.yardId))return send(res,409,{error:'الموقع موجود مسبقًا'});const l={id:id('loc'),yardId:b.yardId||db.yards[0]?.id,name:b.name||b.code,code:b.code,zone:b.zone||'',active:b.active!==false,createdAt:now()};db.locations.push(l);save(db);return send(res,201,l)}
 if(p==='/api/admin/locations'&&method==='PUT'){const u=requireRole(req,res,['ADMIN','MANAGER','YARD','RECEPTION']);if(!u)return;const b=await body(req),l=db.locations.find(x=>x.id===b.id);if(!l)return send(res,404,{error:'الموقع غير موجود'});for(const k of ['name','code','zone','yardId','active'])if(b[k]!==undefined)l[k]=b[k];save(db);return send(res,200,l)}
 if(p==='/api/admin/conditions'&&method==='POST'){const u=requireRole(req,res,['ADMIN','MANAGER','RECEPTION','YARD']);if(!u)return;const b=await body(req),a=asset(b.assetId);if(!a)return send(res,404,{error:'الأصل غير موجود'});const c={id:id('cond'),assetId:a.id,type:b.type||'ENTRY',odometer:b.odometer||'',engineHours:b.engineHours||'',condition:b.condition||'جيدة',accessories:b.accessories||'',notes:b.notes||'',createdAt:now(),userId:u.id};db.conditionReports.push(c);a.updatedAt=now();audit(u,'CREATE','CONDITION',c.id,{assetId:a.id,type:c.type});save(db);return send(res,201,c)}
 if(p==='/api/admin/conditions'&&method==='GET'){const u=requireRole(req,res);if(!u)return;return send(res,200,db.conditionReports.map(c=>({...c,asset:asset(c.assetId)?{title:asset(c.assetId).title,code:asset(c.assetId).code}:null})).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)))}
 if(p==='/api/admin/categories'&&method==='GET'){const u=requireRole(req,res);if(!u)return;return send(res,200,db.categories.sort((a,b)=>a.sortOrder-b.sortOrder))}
 if(p==='/api/admin/categories'&&method==='POST'){const u=requireRole(req,res,['ADMIN','MANAGER']);if(!u)return;const b=await body(req);if(!b.name)return send(res,400,{error:'اسم القسم مطلوب'});const c={id:id('cat'),name:b.name,slug:b.slug||b.name.toLowerCase().replace(/\s+/g,'-'),icon:b.icon||'📦',description:b.description||'',active:b.active!==false,sortOrder:db.categories.length,allowSale:b.allowSale!==false,allowRent:b.allowRent!==false,allowStorage:b.allowStorage!==false,fields:b.fields||[]};db.categories.push(c);save(db);return send(res,201,c)}
 const cm=p.match(/^\/api\/admin\/categories\/([^/]+)$/);if(cm&&method==='PUT'){const u=requireRole(req,res,['ADMIN','MANAGER']);if(!u)return;const c=category(cm[1]);if(!c)return send(res,404,{error:'التصنيف غير موجود'});const b=await body(req);for(const k of ['name','icon','description','active','allowSale','allowRent','allowStorage','fields','sortOrder'])if(b[k]!==undefined)c[k]=b[k];save(db);return send(res,200,c)}
 if(p==='/api/admin/users'&&method==='GET'){const u=requireRole(req,res,['ADMIN','MANAGER']);if(!u)return;return send(res,200,db.users.map(safeUser))}
 if(p==='/api/admin/users'&&method==='POST'){const u=requireRole(req,res,['ADMIN','MANAGER']);if(!u)return;const b=await body(req);if(!b.name||!b.phone)return send(res,400,{error:'الاسم والجوال مطلوبان'});let x=db.users.find(v=>v.phone===b.phone);if(x){Object.assign(x,{name:b.name,role:b.role||x.role,active:b.active!==false,identityType:b.identityType||x.identityType||'NATIONAL_ID',identityNumber:b.identityNumber??(x.identityNumber||''),email:b.email??(x.email||''),address:b.address??(x.address||'')});if(b.password)x.passwordHash=hashPassword(b.password)}else{x={id:id('usr'),name:b.name,phone:b.phone,passwordHash:hashPassword(b.password||'Owner@12345'),role:b.role||'CUSTOMER',active:b.active!==false,identityType:b.identityType||'NATIONAL_ID',identityNumber:b.identityNumber||'',email:b.email||'',address:b.address||'',createdAt:now()};db.users.push(x)}save(db);return send(res,201,safeUser(x))}
 const um=p.match(/^\/api\/admin\/users\/([^/]+)$/);if(um&&method==='PUT'){const u=requireRole(req,res,['ADMIN','MANAGER']);if(!u)return;const x=user(um[1]);if(!x)return send(res,404,{error:'المستخدم غير موجود'});const b=await body(req);for(const k of ['name','phone','role','active','identityType','identityNumber','email','address'])if(b[k]!==undefined)x[k]=b[k];if(b.password)x.passwordHash=hashPassword(b.password);save(db);return send(res,200,safeUser(x))}
 if(p==='/api/admin/reservations'&&method==='GET'){const u=requireRole(req,res);if(!u)return;return send(res,200,db.reservations.map(r=>({...r,asset:asset(r.assetId)?{id:r.assetId,title:asset(r.assetId).title,code:asset(r.assetId).code}:null,customer:user(r.customerId)?safeUser(user(r.customerId)):null})).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)))}
 const rm=p.match(/^\/api\/admin\/reservations\/([^/]+)$/);if(rm&&method==='PUT'){const u=requireRole(req,res,['ADMIN','MANAGER','SALES']);if(!u)return;const r=db.reservations.find(x=>x.id===rm[1]);if(!r)return send(res,404,{error:'الحجز غير موجود'});const b=await body(req);r.status=b.status||r.status;r.note=b.note??r.note;r.updatedAt=now();const a=asset(r.assetId);if(a){if(r.status==='CONFIRMED')a.status='RESERVED';if(['CANCELLED','REJECTED'].includes(r.status)&&a.status==='RESERVED')a.status='ACTIVE';if(r.status==='COMPLETED'){a.status='RENTED';a.exitAt=now();a.exitReason='RENTED';refreshVisibility(a);if(activeStorage(a))closeStorage(a)}refreshVisibility(a);a.updatedAt=now();addHistory(a,u,null,`تحديث حجز ${r.status}`)}save(db);return send(res,200,r)}
 if(p==='/api/admin/offers'&&method==='GET'){const u=requireRole(req,res);if(!u)return;return send(res,200,db.offers.map(o=>({...o,asset:asset(o.assetId)?{title:asset(o.assetId).title,code:asset(o.assetId).code}:null})).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)))}
 const of=p.match(/^\/api\/admin\/offers\/([^/]+)$/);if(of&&method==='PUT'){const u=requireRole(req,res,['ADMIN','MANAGER','SALES']);if(!u)return;const o=db.offers.find(x=>x.id===of[1]);if(!o)return send(res,404,{error:'العرض غير موجود'});const b=await body(req);if(b.status)o.status=b.status;if(b.amount!==undefined)o.amount=Number(b.amount);o.note=b.note??o.note;o.updatedAt=now();save(db);return send(res,200,o)}
 if(p==='/api/admin/transactions'&&method==='GET'){const u=requireRole(req,res,['ADMIN','MANAGER','ACCOUNTING']);if(!u)return;return send(res,200,db.transactions.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)))}
 if(p==='/api/admin/transactions'&&method==='POST'){const u=requireRole(req,res,['ADMIN','MANAGER','ACCOUNTING']);if(!u)return;const b=await body(req);if(!b.amount||!['INCOME','EXPENSE'].includes(b.type))return send(res,400,{error:'المبلغ ونوع الحركة مطلوبان'});const t={id:id('txn'),type:b.type,category:b.category||'OTHER',amount:Number(b.amount),assetId:b.assetId||null,userId:u.id,description:b.description||'',reference:b.reference||'',createdAt:now()};db.transactions.push(t);audit(u,'CREATE','TRANSACTION',t.id,{type:t.type,amount:t.amount});save(db);return send(res,201,t)}
 if(p==='/api/admin/expenses'&&method==='GET'){const u=requireRole(req,res,['ADMIN','MANAGER','ACCOUNTING']);if(!u)return;return send(res,200,db.expenses.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)))}
 if(p==='/api/admin/expenses'&&method==='POST'){const u=requireRole(req,res,['ADMIN','MANAGER','ACCOUNTING']);if(!u)return;const b=await body(req);const e={id:id('exp'),category:b.category||'OTHER',amount:Number(b.amount||0),description:b.description||'',createdAt:now(),userId:u.id};db.expenses.push(e);db.transactions.push({id:id('txn'),type:'EXPENSE',category:e.category,amount:e.amount,userId:u.id,description:e.description,createdAt:e.createdAt});save(db);return send(res,201,e)}
 if(p==='/api/admin/contracts'&&method==='GET'){const u=requireRole(req,res,['ADMIN','MANAGER','SALES','ACCOUNTING']);if(!u)return;return send(res,200,db.contracts.map(c=>({...c,asset:asset(c.assetId)?{title:asset(c.assetId).title,code:asset(c.assetId).code}:null,commissionValue:commissionValue(c)})).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)))}
 if(p==='/api/admin/contracts'&&method==='POST'){const u=requireRole(req,res,['ADMIN','MANAGER','SALES','ACCOUNTING']);if(!u)return;const b=await body(req),a=asset(b.assetId);if(!a)return send(res,404,{error:'الأصل غير موجود'});const c={id:id('ctr'),assetId:a.id,type:b.type||'BROKERAGE_SALE',partyName:b.partyName||'',partyPhone:b.partyPhone||'',amount:Number(b.amount||0),commissionType:b.commissionType||'FIXED',commissionFixed:Number(b.commissionFixed||0),commissionRate:Number(b.commissionRate||0),terms:b.terms||'',status:'DRAFT',createdAt:now(),userId:u.id};db.contracts.push(c);save(db);return send(res,201,{...c,commissionValue:commissionValue(c)})}
 const ctr=p.match(/^\/api\/admin\/contracts\/([^/]+)$/);if(ctr&&method==='PUT'){const u=requireRole(req,res,['ADMIN','MANAGER','SALES','ACCOUNTING']);if(!u)return;const c=db.contracts.find(x=>x.id===ctr[1]);if(!c)return send(res,404,{error:'العقد غير موجود'});const b=await body(req);for(const k of ['type','partyName','partyPhone','amount','commissionType','commissionFixed','commissionRate','terms','status'])if(b[k]!==undefined)c[k]=['amount','commissionFixed','commissionRate'].includes(k)?Number(b[k]):b[k];c.updatedAt=now();save(db);return send(res,200,{...c,commissionValue:commissionValue(c)})}
 if(p==='/api/admin/invoices'&&method==='GET'){const u=requireRole(req,res,['ADMIN','MANAGER','ACCOUNTING','SALES']);if(!u)return;return send(res,200,db.invoices.map(i=>({...i,asset:asset(i.assetId)?{title:asset(i.assetId).title,code:asset(i.assetId).code}:null,owner:user(i.ownerId)?safeUser(user(i.ownerId)):null})).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)))}
 if(p==='/api/admin/invoices'&&method==='POST'){const u=requireRole(req,res,['ADMIN','MANAGER','ACCOUNTING','SALES']);if(!u)return;const b=await body(req);const inv={id:id('inv'),number:nextInvoiceNo(),type:b.type||'GENERAL',assetId:b.assetId||null,ownerId:b.ownerId||null,partyName:b.partyName||'',partyPhone:b.partyPhone||'',subtotal:Number(b.subtotal||0),discount:Number(b.discount||0),tax:Number(b.tax||0),total:Number(b.total||b.subtotal||0)-Number(b.discount||0)+Number(b.tax||0),paid:Number(b.paid||0),status:'ISSUED',notes:b.notes||'',createdAt:now(),userId:u.id,currency:systemSettings().currency};inv.balance=Math.max(0,inv.total-inv.paid);db.invoices.push(inv);if(inv.paid)db.transactions.push({id:id('txn'),type:'INCOME',category:'INVOICE',amount:inv.paid,assetId:inv.assetId,userId:u.id,description:`سداد فاتورة ${inv.number}`,createdAt:now(),reference:inv.number});save(db);return send(res,201,inv)}
 const invm=p.match(/^\/api\/admin\/invoices\/([^/]+)$/);if(invm&&method==='PUT'){const u=requireRole(req,res,['ADMIN','MANAGER','ACCOUNTING']);if(!u)return;const inv=db.invoices.find(x=>x.id===invm[1]);if(!inv)return send(res,404,{error:'الفاتورة غير موجودة'});const b=await body(req);if(b.paid!==undefined){const diff=Number(b.paid)-Number(inv.paid||0);if(diff>0)db.transactions.push({id:id('txn'),type:'INCOME',category:'INVOICE',amount:diff,assetId:inv.assetId,userId:u.id,description:`دفعة فاتورة ${inv.number}`,createdAt:now(),reference:inv.number});inv.paid=Number(b.paid)}if(b.status)inv.status=b.status;inv.balance=Math.max(0,inv.total-inv.paid);save(db);return send(res,200,inv)}
 if(p==='/api/admin/settings'&&method==='GET'){const u=requireRole(req,res,['ADMIN','MANAGER']);if(!u)return;return send(res,200,systemSettings())}
 if(p==='/api/admin/settings'&&method==='PUT'){const u=requireRole(req,res,['ADMIN','MANAGER']);if(!u)return;const b=await body(req);const allowed=['name','tagline','country','city','whatsapp','phone','email','address','logo','currency','timezone','language','storageDefaultRate'];for(const k of allowed)if(b[k]!==undefined)upsertSetting(k,String(b[k]));if(b.currency&&!currencies.some(c=>c.code===b.currency))return send(res,400,{error:'العملة غير مدعومة'});save(db);return send(res,200,systemSettings())}
 if(p==='/api/admin/notifications'&&method==='GET'){const u=requireRole(req,res);if(!u)return;return send(res,200,db.notifications.filter(n=>n.userId===u.id).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)))}
 if(p==='/api/admin/notifications/read'&&method==='POST'){const u=requireRole(req,res);if(!u)return;for(const n of db.notifications.filter(n=>n.userId===u.id))n.read=true;save(db);return send(res,200,{ok:true})}
 if(p==='/api/admin/inquiries'&&method==='GET'){const u=requireRole(req,res);if(!u)return;return send(res,200,db.inquiries.map(i=>({...i,asset:asset(i.assetId)?{id:i.assetId,title:asset(i.assetId).title,code:asset(i.assetId).code}:null,messages:db.messages.filter(m=>m.inquiryId===i.id).sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt))})).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)))}
 const im=p.match(/^\/api\/admin\/inquiries\/([^/]+)\/messages$/);if(im&&method==='POST'){const u=requireRole(req,res);if(!u)return;const i=db.inquiries.find(x=>x.id===im[1]);if(!i)return send(res,404,{error:'الاستفسار غير موجود'});const b=await body(req);const m={id:id('msg'),inquiryId:i.id,senderId:u.id,body:b.body||'',createdAt:now()};db.messages.push(m);i.status='IN_PROGRESS';i.updatedAt=now();save(db);return send(res,201,m)}
 if(p==='/api/admin/reports/summary'&&method==='GET'){const u=requireRole(req,res,['ADMIN','MANAGER','ACCOUNTING']);if(!u)return;const days=Math.max(1,Number(url.searchParams.get('days')||30)),since=Date.now()-days*86400000;const income=db.transactions.filter(x=>x.type==='INCOME'&&new Date(x.createdAt).getTime()>=since).reduce((s,x)=>s+Number(x.amount||0),0);const expense=db.transactions.filter(x=>x.type==='EXPENSE'&&new Date(x.createdAt).getTime()>=since).reduce((s,x)=>s+Number(x.amount||0),0);const byCat={};for(const a of db.assets.filter(x=>new Date(x.createdAt).getTime()>=since)){const c=category(a.categoryId)?.name||'أخرى';byCat[c]=(byCat[c]||0)+1}return send(res,200,{days,currency:systemSettings().currency,income,expense,net:income-expense,assetsAdded:db.assets.filter(x=>new Date(x.createdAt).getTime()>=since).length,exits:db.assets.filter(x=>x.status==='EXITED'&&new Date(x.exitAt||0).getTime()>=since).length,byCategory:byCat,storageOutstanding:db.storageCharges.reduce((s,c)=>s+Math.max(0,Number(c.balance||0)),0),invoiceOutstanding:db.invoices.reduce((s,i)=>s+Math.max(0,Number(i.balance||0)),0)})}
 if(p==='/api/admin/audit'&&method==='GET'){const u=requireRole(req,res,['ADMIN','MANAGER']);if(!u)return;return send(res,200,db.auditLogs.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,1000))}
 if(p==='/api/admin/export'&&method==='GET'){const u=requireRole(req,res,['ADMIN','MANAGER']);if(!u)return;return send(res,200,{exportedAt:now(),version:'2.1.0',data:db})}
 if(p.startsWith('/uploads/')){const f=path.basename(p.slice('/uploads/'.length));const fp=path.join(uploadDir,f);if(fs.existsSync(fp))return send(res,200,fs.readFileSync(fp),mime[path.extname(fp).toLowerCase()]||'application/octet-stream');return send(res,404,{error:'غير موجود'})}
 const fp=path.join(publicDir,p==='/'?'index.html':p.replace(/^\//,''));if(fs.existsSync(fp)&&fs.statSync(fp).isFile())return send(res,200,fs.readFileSync(fp),mime[path.extname(fp).toLowerCase()]||'application/octet-stream');return send(res,404,{error:'الصفحة غير موجودة'});
}
const server=http.createServer((req,res)=>route(req,res).catch(e=>{console.error(e);send(res,500,{error:'حدث خطأ داخلي'})}));
if(process.argv[1]===fileURLToPath(import.meta.url))server.listen(port,()=>console.log(`Houshak v2.1 running on http://localhost:${port}`));
